- name: Playbook demonstrates disabling firewall on windows servers
  hosts: windows
  tasks:
  - name: Disable firewall
    win_firewall:
      state: enabled 
      profiles:
      - Domain
      - Private
      - Public
